# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique='True', verbose_name='电影标题')),
                ('desc', models.CharField(default='暂无简介', max_length=1000, verbose_name='电影简介')),
                ('online_time', models.DateField(verbose_name='上映日期')),
            ],
        ),
    ]
